/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTrackRouteImport } from './routes/api/track'
import { Route as ApiSearchRouteImport } from './routes/api/search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackRoute = ApiTrackRouteImport.update({
  id: '/api/track',
  path: '/api/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/search': typeof ApiSearchRoute
  '/api/track': typeof ApiTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/search': typeof ApiSearchRoute
  '/api/track': typeof ApiTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/search': typeof ApiSearchRoute
  '/api/track': typeof ApiTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/search' | '/api/track'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/search' | '/api/track'
  id: '__root__' | '/' | '/api/search' | '/api/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiTrackRoute: typeof ApiTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track': {
      id: '/api/track'
      path: '/api/track'
      fullPath: '/api/track'
      preLoaderRoute: typeof ApiTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiTrackRoute: ApiTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
